### ISSUE TITLE
Step files

### ISSUE THREAD

**Issue by ariankhatb** [bigtreetech/H2-Series#3]
the step file downloads are not working, it just takes you to a code page

**Comment by thisiskeithb** [comment]
That's a browser issue. Download the entire repo instead and you'll be able to view the files properly.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/13375512/190328061-747ca042-dc49-4592-8129-ecd11dd1996e.png">

Direct link: https://github.com/bigtreetech/H2-Series/archive/refs/heads/master.zip

**Comment by ariankhatb** [comment]
Thank you, i was also able to just paste the text into a text file and then change it to .step \
